service: yearn

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-export-swagger
  - serverless-aws-documentation

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  customDomain: ${file(./config/serverless/domain.js):${self:custom.currentStage}}
  serverless-offline:
    useChildProcesses: true
  basePath: ""
  swaggerDestinations:
    s3BucketName: "yearn.tools"
    s3KeyName: "swagger/swagger.json"
    acl: public-read
  documentation:
    api:
      info:
        version: "1.01"
        title: Yearn API
        description: Yearn API
      tags:
        - name: Vaults
          description: Vault endpoints
        - name: User
          description: User endpoints (these APIs are specific to a user account)
        - name: Loanscan
          description: Loanscan endpoints (not for general consumption)

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${file(./awsProfile.yml):aws_profile}
functions:
  # /vaults
  vaults:
    handler: services/vaults/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /vaults
          method: get
          cors: true
          documentation:
            summary: Gets all vaults from the vault registry
            tags:
              - Vaults
            description: Vaults are pulled from the vault registry (https://etherscan.io/address/0x3ee41c098f9666ed2ea246f4d2558010e59d63a0). Includes controller/strategy info. Updates once an hour.

  vaults-snapshots:
    handler: services/vaults/snapshots/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /vaults/snapshots
          method: get
          cors: true
          documentation:
            summary: Gets current snapshots of all vaults from the Yearn subgraph
            tags:
              - Vaults
            description: >
              Currently the subgraph is indexing 8 out of 11 vaults. More vaults to be added later.

  vaults-save:
    handler: services/vaults/save/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    timeout: 300

  vaults-apy:
    handler: services/vaults/apy/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /vaults/apy
          method: get
          cors: true
          documentation:
            summary: Gets APY for all vaults
            tags:
              - Vaults
            description: >
              Vault APY is calculated based on the following document: https://hackmd.io/BQChrnqRQ3-HHx-0oZZZug?view

  vaults-apy-save:
    handler: services/vaults/apy/save/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    timeout: 300

  # /user
  user-vaults:
    handler: services/user/vaults/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /user/{userAddress}/vaults
          method: get
          cors: true
          request:
            parameters:
              paths:
                userAddress: true
              querystrings:
                statistics: false
                transactions: false
                showall: false
          documentation:
            summary: Gets all vaults a user has interacted with
            tags:
              - User
            description: >
              Optionally include vault statistics and transactions per user. Valid query param values are "true" and "false"
          pathParams:
            - name: "userAddress"
              description: "User account address. Format: 0x{...}"
          queryParams:
            - name: "transactions"
              description: "Include user vault transactions"
              type: "boolean"
              required: false
            - name: "showall"
              description: "Inclue all vaults (including vaults the user has not interacted with)"
              type: "boolean"
              required: false
            - name: "statistics"
              description: "Include user vault statistics (deposits, withdraws, transfers)"
              type: "boolean"
              required: false

  user-vaults-transactions:
    handler: services/user/vaults/transactions/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /user/{userAddress}/vaults/transactions
          method: get
          cors: true
          request:
            parameters:
              paths:
                userAddress: true
          documentation:
            summary: Gets all user transactions per vault (deposits, withdraws, transferIn, transferOut)
            tags:
              - User
            description: >
              Includes amount/shares, calculated by tracing the Yearn vault contract methods. Transactions come from the Yearn subgraph.
          pathParams:
            - name: "userAddress"
              description: "User account address. Format: 0x{...}"

  user-vaults-statistics:
    handler: services/user/vaults/statistics/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /user/{userAddress}/vaults/statistics
          method: get
          cors: true
          request:
            parameters:
              paths:
                userAddress: true
          documentation:
            summary: Gets vault statistics assocaited with a user. Total earnings, deposits, withdrawals, transfers.
            tags:
              - User
            description: >
              Currently earnings include token transfer events (such as zaps). This should be configurable in the future. Statistics come from the Yearn subgraph.
          pathParams:
            - name: "userAddress"
              description: "User account address. Format: 0x{...}"

  user-vaults-earnings:
    handler: services/user/vault/earnings/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /user/{userAddress}/vaults/earnings
          method: get
          cors: true
          request:
            parameters:
              paths:
                userAddress: true
          pathParams:
            - name: "userAddress"
              description: "User account address. Format: 0x{...}"

  # /loanscan
  loanscan-link:
    handler: services/loanscan/link/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /loanscan/link
          method: get
          cors: true
          documentation:
            summary: Gets LINK vault APY
            tags:
              - Loanscan
            description: >
              LINK APY actually comes from the aLINK vault. aLINK vault cannot be relied on directly due to use of insurance

  loanscan-eth-stable:
    handler: services/loanscan/eth-stable/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /loanscan/ethstable
          method: get
          cors: true
          documentation:
            summary: Gets stablecoin vault APYs and ETH vault APY
            tags:
              - Loanscan
            description: >
              APY for following vaults: ETH, USDC, USDT, TUSD, DAI

  loanscan-ycrv:
    handler: services/loanscan/ycrv/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /loanscan/ycrv
          method: get
          cors: true
          documentation:
            summary: Gets yCrv vault APY aggregated with Curve pool APY
            tags:
              - Loanscan
            description: >
              yCrv APY is an aggregate APY. This API combines vault APY with underlying Curve pool APY. Aggregation formula: ((1 + poolApy) * (1 + vaultApy) - 1) * 100;

  loanscan-crvbtc:
    handler: services/loanscan/crvbtc/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /loanscan/crvbtc
          method: get
          cors: true
          documentation:
            summary: Gets crvBTC vault APY aggregated with Curve pool APY
            tags:
              - Loanscan
            description: >
              crvBTC APY is an aggregate APY. This API combines vault APY with underlying Curve pool APY. Aggregation formula: ((1 + poolApy) * (1 + vaultApy) - 1) * 100;

  loanscan-crvbusd:
    handler: services/loanscan/crvbusd/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - http:
          path: /loanscan/crvbusd
          method: get
          cors: true
          documentation:
            summary: Gets crvBUSD vault APY aggregated with Curve pool APY
            tags:
              - Loanscan
            description: >
              crvBUSD APY is an aggregate APY. This API combines vault APY with underlying Curve pool APY. Aggregation formula: ((1 + poolApy) * (1 + vaultApy) - 1) * 100;
